# Generated by Django 4.2.2 on 2023-06-30 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0002_accountvo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountvo',
            name='import_href',
        ),
    ]
