# Generated by Django 4.2.2 on 2023-06-24 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_conference_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='lan',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='lon',
            field=models.TextField(null=True),
        ),
    ]
